### ISSUE TITLE
Debug mode is open in release verions

### ISSUE THREAD

**Issue by yashkrishnan** [Ashish-Bansal/One-Tap-Facebook-Module#1]
Hello,
Was found that debug mode was kept open in release versions, is there is any particular reason you kept it that way ? This will effectively allow any malicious application to gain full access to the App. Since it is a root/Xposed app with URL logging, the risks could be very high.

`android:debuggable="false"` to the `<application>` element in manifest

**Comment by Ashish-Bansal** [comment]
@yashwanth-krishnan 

Hi Yashwanth,

Well I guess it wouldn't affect One Tap Facebook and Youtube Modules because they are just empty modules and doesn't contain any Activity/Service/foobar. They just contain one Hook file, so they will never run and there won't be any process to which one can attach the debugger. If you still think it's possible to exploit it somehow, I would love to know how that can be done. :)

Thanks!
